apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  labels:
    serving.knative.dev/release: "v0.10.0"
  name: jaeger
  namespace: istio-system
spec:
  storage:
    options:
      es:
        server-urls: http://elasticsearch-logging.knative-monitoring.svc.cluster.local:9200
    type: elasticsearch
  strategy: production

---
apiVersion: v1
kind: Service
metadata:
  labels:
    serving.knative.dev/release: "v0.10.0"
  name: zipkin
  namespace: istio-system
spec:
  ports:
  - name: http
    port: 9411
  selector:
    app: jaeger

---
